version: "3.9"
services:
  db:
    image: postgres:15
    container_name: task-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 2311
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
